# Generated by Django 5.2.5 on 2025-08-25 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_content_file_image_text_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='discription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
